Feature / Drops (WIP)
liteflow-labs/starter-kit pull request #359
Opened 2023-08-09 13:01 UTC by ismailToyran

### Project organization
- Related [trello card](https://trello.com/c/FFkLOSNr/947-growth-hacking-drops)

### Description
Adds drop feature to the starter kit. You can navigate to the drops page to see upcoming, in progress and ended drops.
And drop detail page by clicking cards on drops page to navigate and participate on the drop.

### Checklist
- [ ] Base branch of the PR is `dev`

2023-08-14 05:03 UTC, EmmanuelDrouin commented
@ismailToyran a few initial feedback:

- [ ] Issues with the titles sizes on a drop detail page
  - It seems that either they are too big or too small. I would suggest to adjust the H2, H3, etc. to match the starter kit UI and not follow the previous UI implementation that does not match here
  - Related to: "Mint ended", "minting schedule", "drop title", etc.
  - <img width="366" alt="Screen Shot 2566-08-14 at 11 50 34" src="https://github.com/liteflow-labs/starter-kit/assets/15095289/94e1fe6b-3164-42d4-bd7d-cc0b264214c0">
- [ ] Is it possible for the title (H1) of a drop details page to be "Drops - Collection name"? That would be better compared only drops for SEO, but let me know if this is too complex and time consuming.
  - Do we need an "extra" title here? We don't use titles like that on collection or NFT details pages, so asking for consistency
- [ ] On a drops details page, we are missing the "blockchain info" associated with the collection, like we have on a collection details page. 
  - <img width="129" alt="Screen Shot 2566-08-14 at 11 47 46" src="https://github.com/liteflow-labs/starter-kit/assets/15095289/e961b77e-6492-4dba-80fe-29a463b1c639">
- [ ] For the number selector (to select the quantity to mint), do we already have a component that we can use? The current implementation does not look like a component we are already using (UI wise)
  -  <img width="184" alt="Screen Shot 2566-08-14 at 11 52 33" src="https://github.com/liteflow-labs/starter-kit/assets/15095289/1c6513c5-05b9-4635-af08-258f32a4d536">


**3 UI issues:**
- [ ] Once sign in, but not eligible, the button label display "accept bid"
  - <img width="1264" alt="Screen Shot 2566-08-14 at 11 31 33" src="https://github.com/liteflow-labs/starter-kit/assets/15095289/e359842b-afd9-41ee-9978-d83b33af35f9">
- [ ] The countdown should be display in one line, and not on two lines (we have plenty of space)
  - <img width="216" alt="Screen Shot 2566-08-14 at 11 31 37" src="https://github.com/liteflow-labs/starter-kit/assets/15095289/66ceb8f9-c58b-406a-90ca-6cbb8216b11b">
- [ ] On responsive drops details page, the border is cropped for the cards on the left and right side
  - <img width="361" alt="Screen Shot 2566-08-14 at 11 42 13" src="https://github.com/liteflow-labs/starter-kit/assets/15095289/38c17365-512d-42c8-9f6d-1d69dddb5964">


- [ ] In terms of colors, I would suggest you follow the previous UI implementation to match where to use primary colors, black and gray colors.
- The progress bar should use Primary color
- The sub-text should use gray color
- For the BG color in the "minting" block we could use the same BG color as we are using for the bg media on an NFT detail page (to not have a full white page like right now)
- For the black color use with opacity on the drops page for the card we could reduce it to 70% as it is a bit too dark currently

- [ ] It would be nice also if you can add the hover effect on the card with the zoom in the media use in the bg (similar hover as we are doing on other cards to bring dynamism here)

### Layout proposal
On the Starter kit, the current implementation for the "minting" block and "minting schedule" sections are taking full width.
- <img width="1293" alt="Screen Shot 2566-08-14 at 11 57 09" src="https://github.com/liteflow-labs/starter-kit/assets/15095289/f1e41f6b-67e9-4592-ba6a-815b3a45f4e1">
- To improve the implementation on the starter kit I would love to explore a layout where both sections are displayed next to each other. So "Minting Schedule" displayed on the left (taking 50% width) and the "minting" section displayed next to it on the right (taking 50% width)
  - This will reduce the height of the page and make the UI more accessible UX wise

@ismailToyran Do you have prepared a state when there will be no drops displayed yet? When we release this feature, everyone who wants to leverage it will have an empty page by default before they create their first drop. We need to think about this case and prepare a layout that will not display an empty pages to end-users. 
- We could have a banner displayed on top (like the previous UI implementation) with a text like "Explore exclusive Drops from prominent NFT collections" with a customizable image in the bg for clients to customize. And we could add en empty state bellow it when there are no drops listed.

2023-08-28 02:42 UTC, EmmanuelDrouin commented
> Questions;
> 
> * I've already implemented empty state, similar other one. Do you want me to add banner as well? This one is using starter kit basic empty component
> 
> ![image](https://user-images.githubusercontent.com/33982052/263053643-f1ca221c-0b88-490e-8532-7a678896acf1.png)
> 
> * Do you want me to add hover effect to the cards on drops page? Drop card component only in this case?
> * Let me know what do you think of this component (UI wise)
> 
> ![image](https://user-images.githubusercontent.com/33982052/263054197-bb185c03-41b8-414c-a9c8-fcd1d27af747.png)
> 
> According to your comment about number input, I've simplified that to only use chakra defaults. Let me know if this component needs any UI change (and to your question, no we don't have any component to use it like that on the starter kit)
> 
> * Also removed drop detail page title from the top, it was a mistake indeed 😉

2023-08-28 02:49 UTC, EmmanuelDrouin commented
> I've already implemented empty state, similar other one. Do you want me to add banner as well? This one is using starter kit basic empty component

Good for me to keep this empty state for now as otherwise we need to implement custom design. Let's keep that for later on to focus on the functionality first ;) 

> Do you want me to add hover effect to the cards on drops page? Drop card component only in this case?

Yes, so we start to bring consistency with over effects that we started to use on the starter kit ;)

> Let me know what do you think of this component (UI wise)

Looking good on my side 👍 

> According to your comment about number input, I've simplified that to only use chakra defaults. Let me know if this component needs any UI change (and to your question, no we don't have any component to use it like that on the starter kit)

Perfect looking good 👍 

> Also removed drop detail page title from the top, it was a mistake indeed 😉

Perfect 👍

2023-09-01 14:52 UTC, antho1404 commented
I tried to test using this PR to validate https://github.com/liteflow-labs/liteflow-js/pull/175, but I can't test correctly.
- I don't have access to the current drops
- I cannot create a drop with a price of 0: got the following error: `execution reverted: Provided payment is not equal to quantity * price`
- I cannot create a drop with a price of 0.01
- I cannot edit the current drop to make it more permissive

2023-09-06 08:24 UTC, NicolasMahe commented on components/Drop/DropProgress.tsx
> +        return acc + BigNumber(drop.minted).toNumber()
Let's never convert a BigNumber to a number. Everything must be a BigNumber.

2023-09-06 09:35 UTC, ismailToyran commented on components/Drop/DropProgress.tsx
> +        return acc + BigNumber(drop.minted).toNumber()
reduce function needs number for the calculation on this one.
It's to show total number of NFTs minted.

2023-09-07 03:20 UTC, NicolasMahe commented on components/Drop/DropProgress.tsx
> +        return acc + BigNumber(drop.minted).toNumber()
reduce works with any type you pass to it. Can be updated to something like:
```
drops.reduce((acc, drop) => acc.add(drop.minted), BigNumber.from(0))
```
Same comment for `totalSupply` in this file, ` totalMinted` in file `components/Drop/MintForm/Ended.tsx`, and two `totalSupply` in `convert.ts`.

2023-09-07 03:21 UTC, NicolasMahe commented on components/Drop/DropProgress.tsx
> +      .div(BigNumber(totalSupply))
Can pass string, number and BigNumber types on any functions on BigNumber 
```suggestion
      .div(totalSupply)
```

2023-09-07 03:24 UTC, NicolasMahe commented on components/Drop/DropProgress.tsx
> +import BigNumber from 'bignumber.js'
We usually import BigNumber from ethers:
```suggestion
import { BigNumber } from '@ethersproject/bignumber'
```
If you really need the `bignumber.js` version to handle decimals, then we usually import it like:
```
import { BigNumber as BN } from 'bignumber.js'
```

2023-09-07 03:24 UTC, NicolasMahe commented on components/Drop/MintForm/Ended.tsx
> +import BigNumber from 'bignumber.js'
Please use BigNumber from ethers whenever you don't need to deal with decimals:
```suggestion
import { BigNumber } from '@ethersproject/bignumber'
```

2023-09-07 03:25 UTC, NicolasMahe commented on components/Drop/MintForm/Inprogress.tsx
> +    return BigNumber.from(drop.minted).gte(BigNumber.from(drop.supply))
```suggestion
    return BigNumber.from(drop.minted).gte(drop.supply)
```

2023-09-07 03:36 UTC, NicolasMahe commented on components/Drop/DropProgress.tsx
> +  }, [totalMinted, totalSupply])
To not have to use bignumber.js, you can do multiply by 10000 (basis points), calculate the ration, convert to number (safe because it's a ratio), and then divide by 100 to get the percent:
```suggestion
  const mintPercentage = useMemo(() => {
    if (!totalSupply) return
    return BigNumber.from(totalMinted).mul(10000).div(totalSupply).toNumber() / 100
  }, [totalMinted, totalSupply])
```

2023-09-07 03:41 UTC, NicolasMahe commented on components/Drop/DropProgress.tsx
> +        return acc + BigNumber(drop.minted).toNumber()
If the issue you have is because of numbro, it actually accepts string. So you can convert the BigNumber to string using `totalMinted.toString()`.
I would also test if numbro can accept directly BigNumber, not sure but internally numbro is using a BigNumber lib.

2023-09-07 08:43 UTC, ismailToyran commented on components/Drop/DropProgress.tsx
> +        return acc + BigNumber(drop.minted).toNumber()
Can you let me know how to work with `Infinity`?
Couldn't find `Infinity` on `import { BigNumber } from '@ethersproject/bignumber'`

2023-09-22 03:19 UTC, antho1404 commented
@ismailToyran the core and react libraries have been updated to v1.2.0.
Could you update this PR so we can do a final testing

2023-09-22 07:14 UTC, ismailToyran commented on components/Drop/DropProgress.tsx
> +  }, [totalMinted, totalSupply])
[Remove bignumber.js imports](https://github.com/liteflow-labs/starter-kit/pull/359/commits/80d377f017d0d7ebae6617c8c386a018de3c7e6a)

2023-09-22 07:14 UTC, ismailToyran commented on components/Drop/MintForm/Inprogress.tsx
> +    return BigNumber.from(drop.minted).gte(BigNumber.from(drop.supply))
[Remove bignumber.js imports](https://github.com/liteflow-labs/starter-kit/pull/359/commits/80d377f017d0d7ebae6617c8c386a018de3c7e6a)

2023-09-22 07:14 UTC, ismailToyran commented on components/Drop/MintForm/Ended.tsx
> +import BigNumber from 'bignumber.js'
[Remove bignumber.js imports](https://github.com/liteflow-labs/starter-kit/pull/359/commits/80d377f017d0d7ebae6617c8c386a018de3c7e6a)

2023-09-22 07:14 UTC, ismailToyran commented on components/Drop/DropProgress.tsx
> +import BigNumber from 'bignumber.js'
[Remove bignumber.js imports](https://github.com/liteflow-labs/starter-kit/pull/359/commits/80d377f017d0d7ebae6617c8c386a018de3c7e6a)

2023-09-22 07:20 UTC, ismailToyran commented on components/Drop/DropProgress.tsx
> +        return acc + BigNumber(drop.minted).toNumber()
https://github.com/liteflow-labs/starter-kit/issues/423
Created an issue for this one, to move on with the PR

2023-09-24 05:28 UTC, antho1404 requested changes
I only tested with the UI and didn't review the code fully yet but here are some feedback already:

**Blocker:**
I created a new drop for LO-FI PEPE in the future to test the countdown but I got a really weird behavior

A drop initially ended is now gone from the "Past Drops". Also this new drop created that is upcoming is not visible and instead we have a drop in progress even tho when we click https://nft-test-uaan-e3vldwmle-liteflow.vercel.app/collection/1/0x0fcbd68251819928c8f6d182fc04be733fa94170/drop there is no drop active

I think the query for the drops page is wrong and we get the collections instead of the drops. We should display the drops and then the collection associated and not the other way around

| Before | After |
| --- | --- |
| <img width="1286" alt="Screenshot 2023-09-24 at 12 22 58" src="https://github.com/liteflow-labs/starter-kit/assets/1783126/623be5e1-9afd-4e99-95ca-974e513a6ef9"> | <img width="1357" alt="Screenshot 2023-09-24 at 12 25 06" src="https://github.com/liteflow-labs/starter-kit/assets/1783126/1711426c-ad20-428d-b122-181d8fa7f069"> |


**Improvements:**
- When minting we should redirect to the `/owned` this is confusing to redirect to the `on sale`.
- It's a bit confusing to not arrive on the NFT page when we mint only one but it's ok.

2023-09-24 05:28 UTC, antho1404 commented on components/Countdown/Countdown.tsx
> +  if (isStyled) {
I don't really like the `isStyled` prop. This is basically two different components.
The best way would be to have two different components and all the logic in a hook like `useCountdown(date)`.
Nothing critical, but it could be nice to have. Also, this doesn't need to be done in this PR.

2023-09-30 11:22 UTC, antho1404 commented on convert.ts
> +  invariant(activeDrops.drops.nodes[0], 'drop is required')
Naming is really confusing, these are not the active drops that contain drops, it's a collection that contains drops

2023-09-30 11:22 UTC, antho1404 commented on hooks/useDropTimeline.ts
> +export default function useDropTimeline({ drop }: HookArgs): Timeline {
Timeline is the wrong term here, a timeline should have multiple events. This is a status/timeStatus, also this hook could easily be generalized

2023-09-30 11:22 UTC, antho1404 commented on pages/collection/[chainId]/[id]/drop.gql
> +    mintType
`mintType` is not used and this would remove the custom convert function for the collection

2023-09-30 11:22 UTC, antho1404 commented on pages/collection/[chainId]/[id]/drop.tsx
> +      <Head title={collectionDropDetail?.name || t('drops.title')} />
Missing description and image

2023-09-30 11:22 UTC, antho1404 commented on pages/drops.tsx
> +              ))}
Could group the arrays to make it simpler

2023-09-30 11:32 UTC, antho1404 commented on components/Drop/DropHeader.tsx
> +const DropHeader: FC<Props> = ({ collection, reportEmail }) => {
[f65ac36](https://github.com/liteflow-labs/starter-kit/pull/438/commits/f65ac36855d168d28ea5fcaea58f516f1710793a)

2023-09-30 11:32 UTC, antho1404 commented on components/Drop/DropHeaderSkeleton.tsx
> +const DropHeaderSkeleton: FC = () => {
[f65ac36](https://github.com/liteflow-labs/starter-kit/pull/438/commits/f65ac36855d168d28ea5fcaea58f516f1710793a)

2023-09-30 11:32 UTC, antho1404 commented on components/Drop/DropProgress.tsx
> +  )
[4bab636](https://github.com/liteflow-labs/starter-kit/pull/438/commits/4bab6368258d18da68939768878b93ebdda833b4)

2023-09-30 11:32 UTC, antho1404 commented on components/Drop/MintForm/Ended.tsx
> +      }, 0),
[4bab636](https://github.com/liteflow-labs/starter-kit/pull/438/commits/4bab6368258d18da68939768878b93ebdda833b4)

2023-09-30 11:33 UTC, antho1404 commented on components/Drop/MintForm/Inprogress.tsx
> +      data.quantity === 1
[e67fed5](https://github.com/liteflow-labs/starter-kit/pull/438/commits/e67fed521cf3118a1e0cffb72162a6f6fa02a9f8)

2023-09-30 11:33 UTC, antho1404 commented on convert.ts
> +  invariant(activeDrops.drops.nodes[0], 'drop is required')
[43886a4](https://github.com/liteflow-labs/starter-kit/pull/438/commits/43886a4cb96e4a4f9e74ab347a719fb1296ac335)

2023-09-30 11:33 UTC, antho1404 commented on hooks/useDropTimeline.ts
> +export default function useDropTimeline({ drop }: HookArgs): Timeline {
[1cd2a1b](https://github.com/liteflow-labs/starter-kit/pull/438/commits/1cd2a1b23ac756dd4cf2b8209b01f9d79c3b2b5e)

2023-09-30 11:33 UTC, antho1404 commented on pages/collection/[chainId]/[id]/drop.gql
> +    mintType
[df1e2e2](https://github.com/liteflow-labs/starter-kit/pull/438/commits/df1e2e2b4449351a0e7ed625c5827bbeaf510dad)

2023-09-30 11:33 UTC, antho1404 commented on pages/collection/[chainId]/[id]/drop.tsx
> +      <Head title={collectionDropDetail?.name || t('drops.title')} />
[9c39d15](https://github.com/liteflow-labs/starter-kit/pull/438/commits/9c39d15614d4844e5983b9c35b9bee8058a118e1)

2023-09-30 11:34 UTC, antho1404 commented on pages/drops.tsx
> +              ))}
[a1edb23](https://github.com/liteflow-labs/starter-kit/pull/438/commits/a1edb2322d85b3210bbc2fe4e48ca0830387a1e7)

2023-09-30 11:35 UTC, antho1404 approved these changes
Everything works as expected, there are still a few translation issues and a few suggestions that I put in https://github.com/liteflow-labs/starter-kit/pull/438 but that looks ready to merge to me

2023-10-02 15:30 UTC, ismailToyran commented on components/Modal/MintDrop.tsx
> +            'modal.accept-auction.transaction.signature.description',
Nice catch indeed 😅 
[Translation added to mint drop modal](https://github.com/liteflow-labs/starter-kit/pull/359/commits/8b76425e291498e4840e095afc042d85905c1168)

2023-10-02 15:30 UTC, ismailToyran commented on components/Modal/MintDrop.tsx
> +            Mint
[Translation added to mint drop modal](https://github.com/liteflow-labs/starter-kit/pull/359/commits/8b76425e291498e4840e095afc042d85905c1168)

2023-10-02 15:42 UTC, merged