Bypass not supported medias
liteflow-labs/starter-kit pull request #437
Opened 2023-09-29 17:04 UTC by antho1404

Dependency https://github.com/liteflow-labs/starter-kit/pull/435

Get mimetype from API and automatically fallbacks if the media is not supported

2023-10-04 03:11 UTC, antho1404 reviewed
I'm not sure everything has been deployed, I tested with the different assets in https://github.com/liteflow-labs/starter-kit/pull/435 and I still have the CORB error because we don't have the mimetype (which is normal) but I refreshed the assets and still the mimetype is `null`

@NicolasMahe could you deploy everything or check what's wrong.

2023-10-04 03:11 UTC, antho1404 commented on package.json
> +    "@nft/api-graphql": "^1.0.0-beta.41-prerelease-4",
@NicolasMahe please update the package when released

2023-10-04 04:13 UTC, NicolasMahe requested changes

2023-10-04 04:13 UTC, NicolasMahe commented on components/Token/Media.tsx
> +  }, [fallback, mediaToDisplay])
This doesn't prevent media with not supported mimetype to be "tried" to be display and throwing error in the console. There is a request to the html media before this `useEffect` is executed.

You can check on the following token: https://nft-test-uaan-git-feature-mimetype-detection-liteflow.vercel.app/tokens/1-0xa0c38108bbb0f5f2fb46a2019d7314cce38f3f22-10 (that's the collection with html file issues).

I believe adding a check on the mimetype line 91 will be required:
```ts
  if (
    !mediaToDisplay.mimetype ||
    mediaToDisplay.mimetype.startsWith('image/')
  ) {
    return (
      <Box position="relative" w="full" h="full">
        <Image
          src={mediaToDisplay.url}
          alt={defaultText}
          onError={onImageError}
          fill
          objectFit={fill ? 'cover' : 'contain'}
          sizes={sizes}
          unoptimized={mediaToDisplay.mimetype === 'image/gif'}
        />
      </Box>
    )
  }
```

But then, no media is display after the initial loading until the `useEffect` is executed, that's why I added a loader in PR 431 to "mimic" the initial loader when the asset is loading:
https://github.com/liteflow-labs/starter-kit/pull/431/files#diff-6826b9eab3397084e54d012dd4f022c3e72bddaa990d74d2c491c79645ad04f1R225-R226

---

Another way would be to replace the two `useEffect` that call `setMediaToDisplay` by a better `useMemo` that will return the correct `mediaToDisplay` by checking for errors and mimetype.

2023-10-05 04:58 UTC, antho1404 commented on components/Token/Media.tsx
> +  }, [fallback, mediaToDisplay])
I like the idea of a memo, that was my initial implementation, but it makes everything complicated with a single component. Ideally, we should have a component handling the media/fallback and another for the video/image, and that should be possible, but with the current structure, that won't be possible with a memo.

Good catch on the first render (even tho the request is canceled). Adding the test as you describe will most likely create issues with a token like this https://nft-test-uaan-git-feature-mimetype-detection-liteflow.vercel.app/tokens/97-0xcfbb45ff528c8ff6542887f631a1f704b92cf7db-34081265737503256337038727118962159868999502952850231595345751279127311432018 that will load indefinitely if the media is correctly detected. Which point to my main question you haven't answered on the PR about the media detection that does not work

2023-10-05 05:13 UTC, NicolasMahe commented on components/Token/Media.tsx
>  import { AssetMedia } from '../../hooks/useDetectAssetMedia'
Creating a new thread to answer the following comment:
> I'm not sure everything has been deployed, I tested with the different assets in https://github.com/liteflow-labs/starter-kit/pull/435 and I still have the CORB error because we don't have the mimetype (which is normal) but I refreshed the assets and still the mimetype is null

> @NicolasMahe could you deploy everything or check what's wrong.

The refresh of asset is bypassed on lazy mint asset that have not been minted on chain (not purchased yet). I will check why we implement it like this and try to call syncAsset job anyway. I also need to check how the lazy mint asset are created, I may have forgot to set the mimetype at that time.

In the meantime, you can a non lazy mint asset or purchase the lazy mint asset and then refresh it.

2023-10-05 07:01 UTC, antho1404 commented on components/Token/Media.tsx
>  import { AssetMedia } from '../../hooks/useDetectAssetMedia'
Thanks indeed, I didn't realize that lazyminted was different, I will mint them so I can finalize the testing for all cases

2023-10-06 04:20 UTC, NicolasMahe commented on package.json
> +    "@nft/api-graphql": "^1.0.0-beta.41-prerelease-4",
done

2023-10-07 15:01 UTC, antho1404 commented on components/Token/Media.tsx
>  import { AssetMedia } from '../../hooks/useDetectAssetMedia'
I was able to test everything by minting all the assets, no issue with mimetype detections after mint

2023-10-07 15:03 UTC, antho1404 commented on components/Token/Media.tsx
> +  }, [fallback, mediaToDisplay])
In fact, because the format is tested before, that actually displays a normal error, so all good. We had a problem tho with infinite loading if the fallback was also an unsupported file like 97-0xcfbb45ff528c8ff6542887f631a1f704b92cf7db-34081265737503256337038727118962159868999502952850231599814605654957745054776 but that has been fixed

2023-10-10 04:26 UTC, NicolasMahe approved these changes
Working good 👍 

I would love to spend more time to replace the `useEffect` logic with a unique `useMemo` to avoid the extra loading state (skeleton) when the media's mimetype is known but incompatible (can see this with the SSR of https://nft-test-uaan-git-feature-mimetype-detection-liteflow.vercel.app/tokens/1-0xa0c38108bbb0f5f2fb46a2019d7314cce38f3f22-10) but I cannot find an simple way because of the `imageError` and `videoError` logic.

The current result is already very good and good to merge 👍

2023-10-10 04:27 UTC, merged