Cart system
liteflow-labs/starter-kit pull request #471
Opened 2023-11-07 13:42 UTC by antho1404

- https://github.com/liteflow-labs/starter-kit/pull/460

2023-11-28 05:28 UTC, antho1404 commented on components/CartContext.tsx
> +      // temporary solution: wait 1 second before calling the callbacks
Improve ownership detection

2023-11-29 09:35 UTC, NicolasMahe commented on components/CartContext.tsx
> +      // temporary solution: wait 1 second before calling the callbacks
I put it here because I write it before I see your comment and TODO.

The NFT page behind the cart doesn't seems to update. I notice when buying a single NFT using the cart system. Looking at the graphql queries, I will say the infra is not synced with the trade when the starter-kit refresh the nft.
<img width="1526" alt="Screenshot 2023-11-29 at 16 23 25" src="https://github.com/liteflow-labs/starter-kit/assets/5823445/9e1a1e00-c503-4f5d-9b2f-7f258ae6b6b4">

2023-11-29 09:37 UTC, NicolasMahe approved these changes
Working good 👍 
I reopen a comment about the refresh of NFT that is trigger too early to continue the conversation over there.

!! Batch purchase on LightLink Pegasus is returning error because wrapper is not gas-free yet. I contacted them to add it.

| Test Case                                           | Expected Result                      | Actual Result | Status | Notes |
| --------------------------------------------------- | ------------------------------------ | ------------- | ------ | ----- |
| Add item to cart                                    | Item added successfully              | Working       |        |       |
| Remove item from cart                               | Item removed successfully            | Working       |        |       |
| Clear cart                                          | Cart cleared successfully            | Working       |        |       |
| Add item from various chains                        | Item added successfully              | Working       |        |       |
| Add item with native token                          | Item added successfully              | Working       |        |       |
| Add item with ERC20 token                           | Item added successfully              | Working       |        |       |
| Purchase items with only native token               | Purchase successful                  | Working       |        |       |
| Purchase items with only ERC20 token                | Purchase successful                  | Working       |        |       |
| Purchase items with a mix of ERC20 and native token | Purchase successful                  | Working       |        |       |
| Purchase items with no approval on the ERC20        | Purchase fails/has expected behavior | Working       |        |       |
| Verify account activity                             | Account activity accurate            | Working       |        |       |
| Verify payment in the dashboard                     | Payment reflected correctly          | Working       |        |       |

2023-11-29 10:17 UTC, NicolasMahe requested changes

2023-11-29 10:17 UTC, NicolasMahe commented on pages/index.tsx
>  import ResourcesHomeSection from 'components/HomeSection/Resources'
There is something very weird:
I cannot move from any another page from the homepage. I got the blue loader bar at the top loading forever and my CPU usage increase a lot. This happen only on this PR, not issue on the dev branch.

2023-11-29 10:26 UTC, ismailToyran commented
- [ ] I was at explore page with filtered buy now items. After doing transaction, currently bought item didn't refresh and was still shown on the page. There was a fix for this one but I guess didn't work for me on this batch purchase.
- [ ] While getting approval status of currencies, there is no text on the footer button. Looks buggy.

![image](https://github.com/liteflow-labs/starter-kit/assets/33982052/d4b4f522-e861-437c-89f6-804c0d892da7)
- [ ] Same error as Nicolas, need to manually refresh after navigation from homepage (click link and refresh to navigate) otherwise it doesn't work right now.

Rest is working great as expected.

2023-12-04 15:29 UTC, antho1404 commented on pages/index.tsx
>  import ResourcesHomeSection from 'components/HomeSection/Resources'
This has been fixed here https://github.com/liteflow-labs/starter-kit/pull/499 with explanation of why it happened

2023-12-08 11:29 UTC, EmmanuelDrouin commented
## My testing (WIP)

| Test Case                                           | Expected Result                      | Actual Result | Status | Notes |
| --------------------------------------------------- | ------------------------------------ | ------------- | ------ | ----- |
| Add item to cart                                    | Item added successfully              |  Working             |        |       |
| Remove item from cart                               | Item removed successfully            |  Working             |        |       |
| Clear cart                                          | Cart cleared successfully            |  Working             |        |       |
| Add item from various chains                        | Item added successfully              |  Working             |        |       |
| Add item with native token                          | Item added successfully              |  Working             |        |       |
| Add item with ERC20 token                           | Item added successfully              |  Working             |        |       |
| Purchase items with only native token               | Purchase successful                  |  Working             |        |       |
| Purchase items with only ERC20 token                | Purchase successful                  |  Working             |        |       |
| Purchase items with a mix of ERC20 and native token | Purchase successful                  |               |        |       |
| Purchase items with no approval on the ERC20        | Purchase fails/has expected behavior |  Working             |        |       |
| Verify account activity                             | Account activity accurate            |               |        |       |
| Verify payment in the dashboard                     | Payment reflected correctly          |               |        |       |

2023-12-13 05:01 UTC, antho1404 commented on components/CartContext.tsx
> +      // temporary solution: wait 1 second before calling the callbacks
With the current structure that would be a bit complicated but I moved the batch purchase directly into the SDK (js and react) so we can use the polling from there 
PR on liteflow-js https://github.com/liteflow-labs/liteflow-js/pull/202
PR that will merge into this one to update with the library https://github.com/liteflow-labs/starter-kit/pull/504

2024-01-10 07:10 UTC, ismailToyran approved these changes
Let's gooo 🎉

2024-01-10 07:54 UTC, NicolasMahe approved these changes

2024-01-10 07:59 UTC, merged