Feature/number input validation
liteflow-labs/starter-kit pull request #89
Opened 2022-12-13 12:38 UTC by achampagnedev

Related: https://github.com/liteflow-labs/liteflow-js/pull/96

This PR has for goal to reimplement the same changes done to the `liteflow-js`

2022-12-14 08:01 UTC, NicolasMahe commented
I'm putting this PR in draft until https://github.com/liteflow-labs/liteflow-js/pull/96 is merged.
Will be simpler to re-apply the modif once the PR is merged.

2022-12-20 09:43 UTC, NicolasMahe requested changes
Almost there! A few changes and good to merge

2022-12-20 09:43 UTC, NicolasMahe commented on components/Offer/Summary.tsx
> +    quantity?: number | string | BigNumber
I got a 500 errors when going to the bid page of an erc1155:
https://nft-test-polygon-mumbai-git-feature-number-inpu-19b559-liteflow.vercel.app/tokens/80001-0xe3fe92dfec700e7a168f4b074ee7daca71a11397-42728329798185476104569684045014434977602555793693133601813101861374056018692/bid

It's working well on the bid page of a erc721:
https://nft-test-polygon-mumbai-git-feature-number-inpu-19b559-liteflow.vercel.app/tokens/80001-0x7c68c3c59ceb245733a2fdeb47f5f7d6dbcc65b3-42728329798185476104569684045014434977602555793693133601797249465506198024448/bid

I think the reason is this file line 58 is displaying `quantity` without converting it to a string / number first. This doesn't work if it's a BigNumber.
Should be something like:
```
{quantity?.toString()}
```

2022-12-20 09:43 UTC, NicolasMahe commented on hooks/useParseBigNumber.ts
> +      return BigNumber.from(new BN(value).shiftedBy(decimals).toFixed(0))
This function should consider negative BigNumber as incorrect and return zero:
<img width="451" alt="Screenshot 2022-12-20 at 16 04 58" src="https://user-images.githubusercontent.com/5823445/208627286-96dda8a1-0b2b-45eb-9a67-b801e5564c0a.png">

```suggestion
      const valueBN = BigNumber.from(new BN(value).shiftedBy(decimals).toFixed(0))
      if (valueBN.lt(0)) {
        console.error('Value is negative')
        return BigNumber.from(0)
      }
      return valueBN
```

2022-12-20 09:43 UTC, NicolasMahe commented on components/Sales/Direct/Form.tsx
> +        quantity: BigNumber.from(quantityBN),
```suggestion
        quantity: quantityBN,
```

2022-12-20 09:43 UTC, NicolasMahe commented on components/Offer/Summary.tsx
> +    quantity?: number | string | BigNumber
Also some simplification in this file can be done if you change the type of quantity to:
```suggestion
    quantity: BigNumber
```
This only requires to pass `quantityBN` in `Checkout.tsx` as well.
This will remove the try catch needed line 22-27.
The whole totalPrice can be simply:
```tsx
const totalPrice = useMemo(() => price.mul(quantity), [quantity, price])
```
And `if (!totalPrice) return BigNumber.from(0)` can be removed from `totalFees`'s useMemo

2022-12-20 09:43 UTC, NicolasMahe commented on components/Token/Form/Create.tsx
> +                validate: (value) => {
Missing the validation of the number of decimals. Let's put it to 2 decimals.

2022-12-20 09:43 UTC, NicolasMahe commented on pages/explore.tsx
> +                <FormControl isInvalid={!!errors.minPrice || !!errors.maxPrice}>
Would it be possible to have one FormControl per input?
Right now, if one is invalid, both are displayed "red"
<img width="451" alt="Screenshot 2022-12-20 at 16 40 19" src="https://user-images.githubusercontent.com/5823445/208634808-09f0f7af-c460-4de0-8a55-6cd6b580be81.png">

2022-12-20 13:05 UTC, achampagnedev commented on components/Offer/Form/Bid.tsx
> +import useParseBigNumber from 'hooks/useParseBigNumber'
isn't it just absolute vs relative?

2022-12-21 08:03 UTC, NicolasMahe commented on components/Offer/Form/Bid.tsx
> +import useParseBigNumber from 'hooks/useParseBigNumber'
absolute path starts with `/`. This is a relative path from the root folder... a weird mix.

2022-12-21 08:12 UTC, NicolasMahe approved these changes

2022-12-21 08:12 UTC, NicolasMahe commented
@achampagnedev Good job, everything works great!

2022-12-21 08:13 UTC, merged

2022-12-22 09:15 UTC, NicolasMahe commented on pages/explore.tsx
`parsePrice` is used in this file.